### ISSUE TITLE
Packaging fails on .NET framwork despite netstandard target

### ISSUE THREAD

**Issue by mgravell** [Giorgi/DuckDB.NET#151]
I see that there's a `netstandard2.0` package in the nuget, but: it doesn't seem to work; it doesn't work in the tests here, and doesn't work in standalone packages either.

If it isn't *expected* to work on netfx, it might be worth simply dropping the netstandard2.0 target - but this might just be a packaging snafu

test setup example:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DuckDB.NET.Data.Full" Version="0.9.0.3"/>
    </ItemGroup>
</Project>
```

with:

``` csharp
using DuckDB.NET.Data;

using var conn = new DuckDBConnection("Data Source=:memory:");
conn.Open();
```

gives:

``` txt
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'duckdb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DuckDB.NET.NativeMethods.Startup.DuckDBOpen(String path, DuckDBDatabase& database, DuckDBConfig config, IntPtr& error)
   at DuckDB.NET.Data.Internal.ConnectionManager.GetConnectionReference(DuckDBConnectionString connectionString)
   at DuckDB.NET.Data.DuckDBConnection.Open()
   at Program.<Main>$(String[] args) in C:\Code\ConsoleApp7\ConsoleApp7\Program.cs:line 4
```

The packaging might not be right. I haven't looked to see *what* you're packaging and how - it doesn't look like there are native binaries *in the nupkg itself*, so I'm guessing that they are embedded resources in the dll? You *might* prefer to embed them in the nupkg rather than the dll; I also haven't checked to see how the unmanaged dll works re cross-platform (normally I'd expect to see a bunch of platform-specific native dlls in the nupkg, for this purpose)

**Comment by mgravell** [comment]
ah, I understand - editing hugely...

**Comment by Giorgi** [comment]
When PlatformTarget is AnyCpu or x86 the process is still 64-bit but duckdb.dll doesn't get copied to the output folder so I think adding a `Environment.Is64BitProcess` won't help at runtime.

![image](https://github.com/Giorgi/DuckDB.NET/assets/580749/c671f7a9-5561-4553-a610-c749fd243d8d)

**Comment by mgravell** [comment]
Suggestion: if the library has `<PlatformTarget>x64</PlatformTarget>`, it *can't be referenced* from an incompatible project - it gives an error message about the mismatch

**Comment by Giorgi** [comment]
Ah I didn't know that. For Linux, there is only a 64bit binary so will it be a problem?

**Comment by mgravell** [comment]
I don't know, honestly
