### ISSUE TITLE
Failed to download extension (Motherduck)

### ISSUE THREAD

**Issue by wub** [Giorgi/DuckDB.NET#207]
When using Motherduck on macOS 14.5, with .NET 8 and v1.0.2 of this package (.Full), I get:
```sh
DuckDB.NET.Data.DuckDBException (0x00000001): DuckDBOpen failed: IO Error: Failed to download extension "motherduck" at URL "http://extensions.duckdb.org/v1.0.0/osx_arm64/motherduck.duckdb_extension.gz"
Extension "motherduck" is an existing extension.
 (ERROR Connection)
   at DuckDB.NET.Data.Internal.ConnectionManager.GetConnectionReference(DuckDBConnectionString connectionString)
   at DuckDB.NET.Data.DuckDBConnection.Open()
```

If I install the motherduck extension and try again, I get this:
```sh
DuckDB.NET.Data.DuckDBException (0x00000001): DuckDBOpen failed: Invalid Input Error: Initialization function "motherduck_init" from file "/Users/xxx/.duckdb/extensions/v1.0.0/osx_arm64/motherduck.duckdb_extension" threw an exception: "Failed to download "http://api.motherduck.com/extension_version" (attempt 5): Connection"
   at DuckDB.NET.Data.Internal.ConnectionManager.GetConnectionReference(DuckDBConnectionString connectionString)
   at DuckDB.NET.Data.DuckDBConnection.Open()
```
I can't see any logs in the firewall, and no access prompts came up. Any ideas would be appreciated, thank you.

**Comment by wub** [comment]
I found this in the system logs - looks like it's not related to this lib.
`Sandbox: logd_helper(11874) deny(1) file-read-data /Users/xxx/.duckdb/extensions/v1.0.0/osx_arm64/motherduck.duckdb_extension`
