### ISSUE TITLE
Can't query Dates with Dapper `Object must implement IConvertible`

### ISSUE THREAD

**Issue by MeltyObserver** [Giorgi/DuckDB.NET#227]
When trying to query a row with a Date column using dapper i get `Object must implement IConvertible` but it works fine with ADO.Net

Full exception:

<details>

```
Error parsing column 2 (creationDate=11/14/2024 - Object)
--------------
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserializebf872d3d-40a6-4be7-bb5e-31af6c01baa4(DbDataReader)
--------------
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3928
   at Deserializebf872d3d-40a6-4be7-bb5e-31af6c01baa4(DbDataReader)
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Program.<Main>$(String[] args)
```

</details>

I wrote an example project that can reproduce the bug https://github.com/MeltyObserver/DDB.NET.Examples

**Comment by Giorgi** [comment]
Try changing the property to `DateOnly`

**Comment by Giorgi** [comment]
Try this: https://github.com/DapperLib/Dapper/issues/1715#issuecomment-1149665776

**Comment by MeltyObserver** [comment]
That does work, I thought the issue was from this library because i didn't have an issue with postgres (npgsql)

is it possible to add this to the library?

**Comment by Giorgi** [comment]
No, I can't fix, as there isn't anything to fix it. The reason your original code throws is that DuckDB.Net [maps Date column to `DateOnly`](https://github.com/Giorgi/DuckDB.NET/blob/8b6980cb275540e7807425eff7d34d4bd8a76556/DuckDB.NET.Data/Internal/Reader/VectorDataReaderBase.cs#L131) as since your property is `DateTime`, Dapper tries to convert the `DateOnly` value to `DateTime`. `DateOnly` doesn't implement `IConvertible` so you get that exception.

It works in Postgres as Npgsql maps Date column to `DateTime`, probably for compatibility reasons.

You'll have to wait until Dapper adds support for `DateOnly` or use the workaround from the linked Dapper issue.
