### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by maikgroenewegen** [Giorgi/DuckDB.NET#25]
### Description

Running on M1 Mac with .NET6 (6.0.203) using self build libduckdb.dylib (arm64) from recent master.
Samples project fails at line 43: PrintQueryResults(reader); 

The actual error happens in DuckDBNativeObjects.cs line 93: var column = Marshal.PtrToStructure<DuckDBColumn>(columns + Marshal.SizeOf<DuckDBColumn>() * i);
(a
The error message is:

`Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)
   at System.Runtime.InteropServices.Marshal.PtrToStructure[T](IntPtr ptr)`

Earlier actions (creating table, inserting data) seem to be successful when I check the file.db database using DuckDB CLI.

**Comment by Giorgi** [comment]
Looks like the latest duckdb has some breaking changes for querying data: [duckdb.h](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h#L195)

You should be able to make it work if you compile it with `DUCKDB_API_VERSION < DUCKDB_API_0_3_2` until I update the library

**Comment by Giorgi** [comment]
Alternatively you can compile one of the earliest release that doesn't have that breaking change.

**Comment by maikgroenewegen** [comment]
Compiled an older version (0.3.1) of DuckDB and that seems to work with the current version of DuckDB.NET. I do encounter an other error in Dapper when running line 45:

`var results = duckDBConnection.Query<FooBar>("SELECT foo, bar FROM integers");` 

An unhandled exception of type 'System.NullReferenceException' occurred in Dapper.dll: 'Object reference not set to an instance of an object.' but I can leave that be for now.

**Comment by Giorgi** [comment]
Can you post the full stack trace of that exception?

**Comment by maikgroenewegen** [comment]
This is stack trace. I'm using Dapper version 2.0.123
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Dapper.dll: 'Object reference not set to an instance of an object.'
   at Dapper.SqlMapper.<QueryImpl>d__140`1.<>m__Finally1() in /_/Dapper/SqlMapper.cs:line 1137
   at Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in /_/Dapper/SqlMapper.cs:line 1123
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734
```
